version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      # Check for updates managed by Composer once a week
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "internal(pkg): "
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/website/"
    open-pull-requests-limit: 0
    schedule:
      # Check for updates managed by Composer once a week
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "internal: "
