version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      time: "22:00"
      timezone: "America/Chicago"
    labels:
      - "packages"
    allow:
      - dependency-type: "production"
      - dependency-type: "direct"
    ignore:
      - dependency-name: "whatwg-fetch"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-test-renderer"
      - dependency-name: "react-refresh"
    commit-message:
      prefix: "pkg: "
    versioning-strategy: "increase"
